---
type: docker
kind: pipeline
name: default

steps:
  - name: Go test
    image: golang:1.14
    environment:
      GO111MODULE: "on"
    commands:
      - go mod download
      - go test ./... --cover --count=100

trigger:
  event:
    - push
